const PDFS = {
  ORIONE_OBRAS_BRASIL_1: "http://www.bixiga.com.br/museu-temp/assets/FASC1.pdf",
  ORIONE_OBRAS_BRASIL_2: "http://www.bixiga.com.br/museu-temp/assets/Fasc2.pdf",
  ORIONE_OBRAS_BRASIL_3: "http://www.bixiga.com.br/museu-temp/assets/FASC3.pdf",
  ORIONE_OBRAS_BRASIL_4: "http://www.bixiga.com.br/museu-temp/assets/FASC4.pdf",
  ORIONE_OBRAS_BRASIL_5: "http://www.bixiga.com.br/museu-temp/assets/obras_orionitas_Sul_Brasil.pdf",
  ORIONE_OBRAS_BRASIL_6: "http://www.bixiga.com.br/museu-temp/assets/lista_falecidos",
  ORIONE_OBRAS_BRASIL_7: "http://www.bixiga.com.br/museu-temp/assets/falecidos_do_Brasil.pdf",
  ORIONE_PUBLICACOES_BOLETIM: "http://www.bixiga.com.br/museu-temp/assets/Peq_Obra_Orione.pdf",
  ORIONE_PUBLICACOES_LIVROS_1: "http://www.bixiga.com.br/museu-temp/assets/Orione_quadrinho.pdf",
  ORIONE_PUBLICACOES_LIVROS_2: "http://www.bixiga.com.br/museu-temp/assets/livro_perolas.pdf",
  ORIONE_PUBLICACOES_LIVROS_3: "http://www.bixiga.com.br/museu-temp/assets/novena_orione.pdf",
  ORIONE_PUBLICACOES_LIVROS_4: "http://www.bixiga.com.br/museu-temp/assets/orione_belas_paginas.pdf",
  ORIONE_PUBLICACOES_LIVROS_5: "http://www.bixiga.com.br/museu-temp/assets/orione_encantador.pdf",
  ORIONE_PUBLICACOES_LIVROS_6: "http://www.bixiga.com.br/museu-temp/assets/geo-livro1.pdf",
  ORIONE_PUBLICACOES_LIVROS_7: "http://www.bixiga.com.br/museu-temp/assets/geo-livro2.pdf",
  ORIONE_PUBLICACOES_LIVROS_8: "http://www.bixiga.com.br/museu-temp/assets/geo-livro3.pdf",
  ORIONE_PUBLICACOES_LIVROS_9: "http://www.bixiga.com.br/museu-temp/assets/geo-livro4.pdf",
  ORIONE_PUBLICACOES_LIVROS_10: "http://www.bixiga.com.br/museu-temp/assets/geo-livro5.pdf",
  ORIONE_PUBLICACOES_LIVROS_11: "http://www.bixiga.com.br/museu-temp/assets/geo-livro6.pdf",
  ORIONE_PUBLICACOES_LIVROS_12: "http://www.bixiga.com.br/museu-temp/assets/geo-livro7.pdf",
  ORIONE_PUBLICACOES_LIVROS_13: "http://www.bixiga.com.br/museu-temp/assets/geo-livro8.pdf",
  ORIONE_PUBLICACOES_LIVROS_14: "http://www.bixiga.com.br/museu-temp/assets/nossos_santos_altar.pdf",
  ORIONE_PUBLICACOES_LIVROS_15: "http://www.bixiga.com.br/museu-temp/assets/orione-idiomas-livro1.pdf",
  ORIONE_PUBLICACOES_LIVROS_16: "http://www.bixiga.com.br/museu-temp/assets/orione-idiomas-livro2.pdf",
  ORIONE_PUBLICACOES_LIVROS_17: "http://www.bixiga.com.br/museu-temp/assets/orione-idiomas-livro3.pdf",
  ORIONE_PUBLICACOES_LIVROS_18: "http://www.bixiga.com.br/museu-temp/assets/orione-idiomas-livro4.pdf",
  ORIONE_PUBLICACOES_LIVROS_19: "http://www.bixiga.com.br/museu-temp/assets/orione-idiomas-livro5.pdf",
  ORIONE_PUBLICACOES_LIVROS_20: "http://www.bixiga.com.br/museu-temp/assets/revista_mocambique.pdf",

  ACHIROPITA_PAROQUIA_PASTORAL_26: "http://www.bixiga.com.br/museu-temp/assets/pastoral-betel.pdf",
  ACHIROPITA_LIVROS_1: "http://www.bixiga.com.br/museu-temp/assets/nossas_devocoes.pdf",
  ACHIROPITA_LIVROS_2: "http://www.bixiga.com.br/museu-temp/assets/maria_beleza_infinita.pdf",
  ACHIROPITA_LIVROS_3_INTRODUCAO: "http://www.bixiga.com.br/museu-temp/assets/intro_poemas.pdf",
  ACHIROPITA_LIVROS_4: "http://www.bixiga.com.br/museu-temp/assets/livro_jesus.pdf",
};

export default PDFS;